
#time, in ticks, to delay the task of passing of night
sleepDelay: 60

#server time to stop at for passing night
stopTime: 23450

#amount to increment by
increment: 10

#whether to show sleep message to players in other world,
# such as the nether or the end.
showMessageToOtherWorld: false

#whether to allow players in other worlds to call wakeup,
# such as the nether or the end.
# allows kick from all worlds
allowKickFromOtherWorld: false

#whether to fully kick a player from a bed on wakeup call,
# which may make it harder for a player to stop phantom spawns.
kickFromBed: true


randomPerPlayer: false

#DO NOT TOUCH VERSION NUMBER
version: 0.1
