#time, in ticks, to delay the task of passing of night
# if night is not passed, weather is cleared after 2x this amount
sleepDelay: 60

#server time to allow passing night
startTime: 12542
stopTime: 23450

#amount of time to increment by
increment: 75

#option to sync all worlds on sleep task
globalNightSkipSync: false

#whether to show sleep message to players in other world,
# such as the nether or the end.
showMessageToOtherWorld: false

#whether to allow players in other worlds to call wakeup,
# such as the nether or the end.
# allows kick from all worlds
allowKickFromOtherWorld: false

#whether to fully kick a player from a bed on wakeup call,
# which may make it harder for a player to stop phantom spawns.
kickFromBed: true

#whether to reset statistics for every player on sleep task
resetAllStatistics: true

#whether to randomize the message for every player 
#   instead of distributing 1 random message
randomPerPlayer: false

#DO NOT TOUCH VERSION NUMBER
version: 1.2
