name: OnePlayerSleep
main: OnePlayerSleep.OnePlayerSleep.OnePlayerSleep
version: 3.0
api-version: 1.13
author: leaf26
website: https://github.com/DailyStruggle

softdepend: [PlaceholderAPI]

commands:
    sleep:
        description: sleep help
        usage: |
            /sleep
    sleep help:
        description: sleep help
        permission: sleep.see
        usage: |
            /sleep help
    sleep reload:
        description: Reloads the plugin configuration files
        permission: sleep.reload
        usage: |
            /sleep reload
    sleep test:
        description: test a sleep message
        permission: sleep.test
        usage: |
            /sleep test
    sleep wakeup:
        description: kick from bed
        permission: sleep.wakeup
        usage: |
            /sleep wakeup

permissions:
    sleep.*:
        description: allows use of all sleep commands
        default: op
        children:
            sleep.see: true
            sleep.reload: true
            sleep.wakeup: true
            sleep.bypass: true
            sleep.test: true
            sleep.withoutBed: true
    sleep.see:
        description: can see the sleep help menu
        default: true
    sleep.reload:
        description: can reload sleep options
        default: op
    sleep.wakeup:
        description: can kick others from bed
        default: true
    sleep.bypass:
        description: cannot kick this player from bed
        default: op
    sleep.test:
        description: can run a sleep message in chat
        default: op
    sleep.ignore:
        description: ignore player entirely
        default: false